/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabAssistant;


import Business.EcoSystem;
import Business.Organization.LabOrganization;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.ManufacturedKits;
import Business.WorkQueue.ManufacturingWorkResult;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;


/**
 *
 * @author Abhilash Wase
 */
public class LabAssistantWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest request;
    EcoSystem business;
    private LabOrganization labOrganization;
    ArrayList<WorkRequest> result =new ArrayList<WorkRequest>();
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public LabAssistantWorkAreaJPanel(JPanel userProcessContainer, EcoSystem business,LabTestWorkRequest request,LabOrganization labOrganization) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.business = business;
        this.labOrganization = labOrganization;
        result = labOrganization.getWorkQueue().getWorkRequestList();
        
    }
    
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kitsTotalJText = new javax.swing.JTextField();
        kitsApprovedJText = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lab Assistant Work Area - Test Request");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 780, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("No. Of Kits :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Total Quantity");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("Approved Quantity");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        kitsTotalJText.setEnabled(false);
        add(kitsTotalJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 50, -1));
        add(kitsApprovedJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 50, -1));

        submitJButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        backJButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField kitsApprovedJText;
    private javax.swing.JTextField kitsTotalJText;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
